-- R31: same-count content updates and repeated Find requests have identities.
local h = require('test/helpers')
local src, dst = h.tmpdir('review_events_src'), h.tmpdir('review_events_dst')
h.mkdir(src); h.mkdir(dst); h.create_file(src .. '/entry', 'first')
h.cd(src, dst); h.ensure_left_focus()
fc.wait_event('__drain__', 20)
assert(os.rename(src .. '/entry', src .. '/renamed'))
fc.cmd('refresh_dir')
assert(fc.wait_event('items_updated', 2000))
assert(fc.state().left.item_count == 1)
fc.wait_event('__drain__', 20)
h.create_file(src .. '/renamed', 'longer replacement contents')
fc.cmd('refresh_dir')
assert(fc.wait_event('items_updated', 2000))
assert(fc.state().left.item_count == 1)
fc.cmd('find'); assert(fc.wait_event('dialog_opened', 1000, 'Find'))
fc.key('ret')
local ok1, id1 = fc.wait_event('find_completed', 2000)
assert(ok1)
fc.key('ret')
local ok2, id2 = fc.wait_event('find_completed', 2000)
assert(ok2 and id1 ~= id2, 'repeated Find completion was lost or replayed')
fc.key('esc')
h.cleanup(src, dst)
test_pass('review_events')
