local h = require('test/helpers')
local root = h.tmpdir("-- quote' newline\nΩ")
h.mkdir(root)
h.mkdir(root)
local target = "-- target'\nΩ"
h.create_file(root .. '/' .. target, 'binary\0bytes\255')
h.create_symlink(target, root .. "/link'\n")
check(h.dir_exists(root), 'quoted directory missing')
check(h.count_items(root) == 2, 'newline counted as multiple entries')
check(h.read_symlink(root .. "/link'\n") == target, 'raw link target changed')
check(h.read_file(root .. '/' .. target) == 'binary\0bytes\255', 'binary bytes changed')
check(h.tree_manifest(root):find('sha256', 1, true), 'manifest missing hash')
h.rmdir(root)
h.rmdir(root)
check(not h.dir_exists(root), 'fixture cleanup failed')
test_pass('fixture_paths')
fc.quit()
