# Keep CTest labels and lane qualification driven by the same reviewed list.
function(fc_label_manual_tests)
  if(NOT BUILD_TESTING)
    return()
  endif()
  set(_manifest "${CMAKE_CURRENT_SOURCE_DIR}/test/release_required.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_manifest}")
  file(READ "${_manifest}" _registry)
  string(JSON _count LENGTH "${_registry}" manual)
  if(_count EQUAL 0)
    return()
  endif()
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name GET "${_registry}" manual ${_index})
    if(TEST "${_name}")
      set_property(TEST "${_name}" APPEND PROPERTY LABELS manual)
    endif()
  endforeach()
endfunction()
