# Registry-driven discovery: each case owns a process, config and deadline.
file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/test/review_cases.inc" _review_cases REGEX "^FC_REVIEW_CASE")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/test/review_cases.inc"
  "${CMAKE_CURRENT_SOURCE_DIR}/test/lua_suites.json"
  "${CMAKE_CURRENT_SOURCE_DIR}/test/negative_controls.json")
foreach(_case IN LISTS _review_cases)
  string(REGEX MATCH "FC_REVIEW_CASE\\(([A-Za-z0-9_]+), \"([^\"]+)\"\\)" _match "${_case}")
  set(_id "${CMAKE_MATCH_1}")
  set(_name "${CMAKE_MATCH_2}")
  add_test(NAME "fc.regression.${_name}" COMMAND fc_review_tests "${_id}")
  set_tests_properties("fc.regression.${_name}" PROPERTIES LABELS "regression;native;integration;${_id}" TIMEOUT 45)
endforeach()

if(UNIX AND NOT CMAKE_CROSSCOMPILING)
  find_package(Python3 3.12 COMPONENTS Interpreter REQUIRED)
  foreach(_check result_checks protocol manifests supervisor)
    add_test(NAME "fc.harness.${_check}" COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test/test_${_check}.py" $<TARGET_FILE:fc>)
    set_tests_properties("fc.harness.${_check}" PROPERTIES LABELS "unit;harness" TIMEOUT 40)
  endforeach()
  file(READ "${CMAKE_CURRENT_SOURCE_DIR}/test/lua_suites.json" _suites)
  string(JSON _count LENGTH "${_suites}")
  math(EXPR _last "${_count}-1")
  foreach(_index RANGE ${_last})
    string(JSON _id MEMBER "${_suites}" ${_index})
    string(JSON _script GET "${_suites}" ${_id} script)
    string(JSON _cases LENGTH "${_suites}" ${_id} cases)
    if(_cases GREATER 0)
      math(EXPR _last_case "${_cases}-1")
      foreach(_n RANGE ${_last_case})
        string(JSON _case GET "${_suites}" ${_id} cases ${_n})
        add_test(NAME "fc.lua.${_id}.${_case}" COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test/run_lua_suite.py"
          --binary $<TARGET_FILE:fc> --logs "${CMAKE_CURRENT_BINARY_DIR}/test-logs/lua" --suite "${_id}" --case "${_case}" "${_script}")
        set_tests_properties("fc.lua.${_id}.${_case}" PROPERTIES LABELS "integration;lua;pty;posix" TIMEOUT 130)
      endforeach()
    else()
      add_test(NAME "fc.lua.${_id}" COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test/run_lua_suite.py"
        --binary $<TARGET_FILE:fc> --logs "${CMAKE_CURRENT_BINARY_DIR}/test-logs/lua" --suite "${_id}" "${_script}")
      set_tests_properties("fc.lua.${_id}" PROPERTIES LABELS "integration;lua;pty;posix" TIMEOUT 130)
    endif()
  endforeach()
  file(READ "${CMAKE_CURRENT_SOURCE_DIR}/test/negative_controls.json" _controls)
  string(JSON _count LENGTH "${_controls}")
  math(EXPR _last "${_count}-1")
  foreach(_index RANGE ${_last})
    string(JSON _id MEMBER "${_controls}" ${_index})
    add_test(NAME "fc.negative.${_id}" COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test/run_lua_suite.py"
      --binary $<TARGET_FILE:fc> --logs "${CMAKE_CURRENT_BINARY_DIR}/test-logs/negative" --negative-case "${_id}")
    set_tests_properties("fc.negative.${_id}" PROPERTIES LABELS "integration;negative;pty;posix" TIMEOUT 130)
  endforeach()
  foreach(_case syntax runtime returned yield_watchdog loop_watchdog long_sleep long_wait)
    add_test(NAME fc.process_exit.${_case} COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test/test_script_exit.py"
      $<TARGET_FILE:fc> --case ${_case} --logs "${CMAKE_CURRENT_BINARY_DIR}/test-logs/exit")
    set_tests_properties(fc.process_exit.${_case} PROPERTIES LABELS "integration;pty;posix" TIMEOUT 15)
  endforeach()
endif()
